import { BankItem, mcq } from './types';

export const BIOLOGY_ITEMS: BankItem[] = [
  mcq('Which organelle is responsible for the synthesis of ATP through aerobic respiration?', 'Cell Biology', ['Golgi apparatus', 'Mitochondrion', 'Ribosome', 'Lysosome'], 1),
  mcq('The enzyme that catalyses the breakdown of starch into maltose is called', 'Enzymes', ['Lipase', 'Pepsin', 'Amylase', 'Trypsin'], 2),
  mcq('During photosynthesis, the light-dependent reactions occur in the', 'Photosynthesis', ['Stroma', 'Thylakoid membrane', 'Mitochondrial matrix', 'Cytoplasm'], 1),
  mcq('In plants, water and mineral salts are transported mainly through the', 'Transport in Plants', ['Phloem', 'Xylem', 'Cambium', 'Cortex'], 1),
  mcq('The chamber of the human heart that pumps oxygenated blood to the whole body is the', 'Human Physiology', ['Right atrium', 'Left atrium', 'Right ventricle', 'Left ventricle'], 3),
  mcq('Which gas is released as a by-product of anaerobic respiration in yeast?', 'Respiration', ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], 1),
  mcq('White blood cells that produce antibodies are called', 'Immunity', ['Neutrophils', 'Lymphocytes', 'Platelets', 'Erythrocytes'], 1),
  mcq('A stable community of organisms interacting with their non-living environment is known as a/an', 'Ecology', ['Population', 'Habitat', 'Ecosystem', 'Biome'], 2),
  mcq('An organism with genotype Bb crossed with another Bb will produce offspring in the phenotypic ratio of', 'Genetics', ['1:1', '3:1', '1:2:1', '9:3:3:1'], 1),
  mcq('The process by which a sperm cell fuses with an egg cell is called', 'Reproduction', ['Pollination', 'Fertilisation', 'Implantation', 'Ovulation'], 1),
  mcq('Organisms are classified into the kingdom Fungi mainly because they', 'Classification', ['Manufacture their own food', 'Have cell walls made of cellulose', 'Absorb nutrients from decaying matter', 'Lack a nucleus'], 2),
  mcq('When a red blood cell is placed in a hypertonic solution, it will', 'Osmosis', ['Swell and burst', 'Remain unchanged', 'Shrink and crenate', 'Divide rapidly'], 2),

  { type: 'true_false', text: 'The cell membrane is fully permeable to all substances.', topic: 'Cell Biology', answer: 'False' },
  { type: 'true_false', text: 'Enzymes are biological catalysts made of protein.', topic: 'Enzymes', answer: 'True' },
  { type: 'true_false', text: 'Chlorophyll absorbs green light most strongly for photosynthesis.', topic: 'Photosynthesis', answer: 'False' },
  { type: 'true_false', text: 'In humans, arteries generally carry blood away from the heart.', topic: 'Human Physiology', answer: 'True' },
  { type: 'true_false', text: 'Vaccination introduces antigens to stimulate active immunity.', topic: 'Immunity', answer: 'True' },
  { type: 'true_false', text: 'Meiosis produces two genetically identical diploid daughter cells.', topic: 'Genetics', answer: 'False' },

  { type: 'matching', text: 'Match each cell organelle in Column A with its correct function in Column B.', topic: 'Cell Biology',
    pairs: [
      { left: 'Nucleus', right: 'Controls cell activities and contains genetic material' },
      { left: 'Mitochondrion', right: 'Site of aerobic respiration and ATP production' },
      { left: 'Ribosome', right: 'Site of protein synthesis' },
      { left: 'Chloroplast', right: 'Site of photosynthesis' },
      { left: 'Vacuole', right: 'Stores cell sap and maintains turgor pressure' },
    ] },
  { type: 'matching', text: 'Match each human body system in Column A with its correct function in Column B.', topic: 'Human Physiology',
    pairs: [
      { left: 'Circulatory system', right: 'Transports blood and nutrients around the body' },
      { left: 'Respiratory system', right: 'Enables gaseous exchange of oxygen and carbon dioxide' },
      { left: 'Digestive system', right: 'Breaks down food into absorbable nutrients' },
      { left: 'Excretory system', right: 'Removes metabolic waste products from the body' },
    ] },
  { type: 'matching', text: 'Match each ecological term in Column A with its correct description in Column B.', topic: 'Ecology',
    pairs: [
      { left: 'Producer', right: 'Organism that manufactures its own food by photosynthesis' },
      { left: 'Primary consumer', right: 'Organism that feeds directly on producers' },
      { left: 'Decomposer', right: 'Organism that breaks down dead organic matter' },
      { left: 'Food chain', right: 'A linear sequence showing transfer of energy between organisms' },
      { left: 'Biotic factor', right: 'A living component of an ecosystem' },
    ] },

  { type: 'fill_blank', text: 'The green pigment found in chloroplasts that traps light energy for photosynthesis is called ______.', topic: 'Photosynthesis', answer: 'chlorophyll' },
  { type: 'fill_blank', text: 'The movement of water molecules from a region of high water potential to a region of low water potential through a partially permeable membrane is called ______.', topic: 'Osmosis', answer: 'osmosis' },
  { type: 'fill_blank', text: 'The muscular wave-like contraction that pushes food along the oesophagus is known as ______.', topic: 'Human Physiology', answer: 'peristalsis' },
  { type: 'fill_blank', text: 'A change in the DNA sequence of an organism that may be inherited is called a ______.', topic: 'Genetics', answer: 'mutation' },

  { type: 'short_answer', text: 'State three functions of the liver in the human body.', topic: 'Human Physiology',
    answer: 'Production of bile for fat digestion, deamination of excess amino acids, detoxification of poisons, storage of glycogen, regulation of blood glucose levels.',
    rubric: ['Bile production for emulsification of fats', 'Deamination of excess amino acids/formation of urea', 'Detoxification of harmful substances', 'Storage of glycogen and vitamins'] },
  { type: 'short_answer', text: 'Explain why enzyme activity decreases at temperatures above the optimum.', topic: 'Enzymes',
    answer: 'High temperatures denature the enzyme by breaking hydrogen and other bonds that maintain its tertiary structure, distorting the active site so that the substrate can no longer bind, thus reducing the rate of reaction.',
    rubric: ['High temperature breaks bonds maintaining tertiary structure', 'Active site shape is altered/distorted', 'Substrate can no longer bind (induced-fit lost)', 'Enzyme is denatured and rate falls'] },
  { type: 'short_answer', text: 'Explain three adaptations of red blood cells to their function of transporting oxygen.', topic: 'Transport in Animals',
    answer: 'Biconcave shape increases surface area for gaseous exchange, absence of a nucleus creates more space for haemoglobin, presence of haemoglobin allows binding and transport of oxygen.',
    rubric: ['Biconcave disc shape increases surface area to volume ratio', 'No nucleus provides more room for haemoglobin', 'Contains haemoglobin which binds oxygen reversibly', 'Small and flexible to pass through capillaries'] },
  { type: 'short_answer', text: 'Distinguish between aerobic and anaerobic respiration.', topic: 'Respiration',
    answer: 'Aerobic respiration requires oxygen and completely breaks down glucose to carbon dioxide and water, releasing a large amount of energy, while anaerobic respiration occurs without oxygen and only partially breaks down glucose, releasing a small amount of energy and producing lactic acid or ethanol.',
    rubric: ['Aerobic requires oxygen; anaerobic does not', 'Aerobic releases more energy per glucose molecule', 'Aerobic end products are CO₂ and H₂O', 'Anaerobic end products are lactic acid or ethanol and CO₂'] },
  { type: 'short_answer', text: 'State three ways in which the body defends itself against pathogens.', topic: 'Immunity',
    answer: 'Skin acts as a physical barrier, phagocytes engulf and digest pathogens, lymphocytes produce antibodies against specific antigens, mucus traps microorganisms in the respiratory tract.',
    rubric: ['Skin as a physical/chemical barrier', 'Phagocytosis by white blood cells', 'Antibody production by lymphocytes', 'Mucus and cilia trapping pathogens'] },
  { type: 'short_answer', text: 'Explain three factors that affect the rate of transpiration in a plant.', topic: 'Transport in Plants',
    answer: 'Increased temperature raises the rate of evaporation, increased wind speed removes water vapour from the leaf surface faster, low humidity increases the diffusion gradient, and increased light intensity opens stomata wider.',
    rubric: ['Temperature: higher temperature increases evaporation rate', 'Humidity: lower humidity increases diffusion gradient', 'Wind speed: removes water vapour, maintaining a steep gradient', 'Light intensity: stomata open wider increasing transpiration'] },

  { type: 'structured', text: 'A group of Senior Four students at a school in Musanze District set up an experiment to investigate the effect of light intensity on the rate of photosynthesis using a pondweed (Elodea).',
    topic: 'Photosynthesis',
    parts: [
      { text: 'State the independent variable in this experiment.', answer: 'Light intensity.' },
      { text: 'Explain why the number of bubbles produced by the pondweed increases as the lamp is moved closer.', answer: 'Moving the lamp closer increases light intensity, providing more light energy to drive the light-dependent reactions, thus increasing the rate of photosynthesis and oxygen production.' },
      { text: 'The students varied two other factors to test their effect on photosynthesis.',
        parts: [
          { text: 'Name one such factor.', answer: 'Carbon dioxide concentration (or temperature).' },
          { text: 'State how this factor would be expected to affect the rate of photosynthesis if increased within the normal range.', answer: 'It would increase the rate of photosynthesis, since carbon dioxide is a raw material (or temperature increases enzyme activity) up to the optimum.' },
        ] },
    ] },
  { type: 'structured', text: 'During a biology practical lesson at a school in Huye District, students examined prepared slides of onion epidermal cells before and after immersion in a concentrated salt solution.',
    topic: 'Osmosis',
    parts: [
      { text: 'Define the term osmosis.', answer: 'Osmosis is the movement of water molecules from a region of high water potential to a region of low water potential through a partially permeable membrane.' },
      { text: 'Describe the appearance of the onion cells after immersion in the concentrated salt solution.', answer: 'The cell membrane shrinks away from the cell wall as water leaves the cell by osmosis, a condition called plasmolysis.' },
      { text: 'The students repeated the experiment using distilled water.',
        parts: [
          { text: 'Predict what would happen to the onion cells.', answer: 'The cells would absorb water by osmosis and become turgid, but would not burst due to the presence of the rigid cell wall.' },
          { text: 'Explain why plant cells do not burst under these conditions, unlike animal cells.', answer: 'The cellulose cell wall is rigid and exerts an inward pressure (wall pressure) that resists further water entry once the cell is fully turgid.' },
        ] },
    ] },
  { type: 'structured', text: 'Students in a health club at a school in Rubavu District were taught about blood circulation and carried out a heart dissection using a goat heart provided by a local abattoir.',
    topic: 'Human Physiology',
    parts: [
      { text: 'Name the blood vessel that carries deoxygenated blood from the body into the heart.', answer: 'The vena cava.' },
      { text: 'Explain why the wall of the left ventricle is thicker than that of the right ventricle.', answer: 'The left ventricle pumps blood at high pressure over a long distance to the whole body, whereas the right ventricle only pumps blood to the nearby lungs, so it requires more muscle to generate greater pressure.' },
      { text: 'The students also examined the valves of the heart.',
        parts: [
          { text: 'State the function of the heart valves.', answer: 'To prevent the backflow of blood, ensuring it flows in one direction.' },
          { text: 'Name the valve located between the left atrium and the left ventricle.', answer: 'The bicuspid (mitral) valve.' },
        ] },
    ] },
  { type: 'structured', text: 'A teacher in Nyagatare District carried out a genetic cross demonstration with students using tall (T) and dwarf (t) pea plants, crossing two heterozygous tall parents (Tt × Tt).',
    topic: 'Genetics',
    parts: [
      { text: 'State the genotypic ratio expected in the offspring of this cross.', answer: '1 TT : 2 Tt : 1 tt.' },
      { text: 'Explain why some offspring are dwarf even though both parents are tall.', answer: 'Both parents are heterozygous (Tt) and carry a recessive allele (t) for dwarfism; when two recessive alleles combine in an offspring (tt), the dwarf phenotype is expressed since it is masked in heterozygotes by the dominant tall allele.' },
      { text: 'The teacher then asked about a testcross to confirm the genotype of a tall plant.',
        parts: [
          { text: 'Define the term testcross.', answer: 'A testcross is a cross between an individual of unknown genotype and a homozygous recessive individual, used to determine the unknown genotype.' },
          { text: 'State the expected phenotypic ratio if the tall plant tested were heterozygous.', answer: '1 tall : 1 dwarf.' },
        ] },
    ] },

  { type: 'essay', text: 'Discuss the adaptations of xerophytic plants for survival in arid environments.', topic: 'Transport in Plants',
    rubric: ['Thick waxy cuticle reduces water loss by evaporation', 'Sunken stomata/reduced number of stomata reduces transpiration', 'Reduced leaf surface area (e.g. spines/needle-like leaves) minimises water loss', 'Extensive/deep root systems increase water absorption'] },
  { type: 'essay', text: 'Discuss the role of the human immune system in protecting the body against infectious diseases, and explain the importance of vaccination programmes in Rwanda.', topic: 'Immunity',
    rubric: ['Physical and chemical barriers prevent pathogen entry', 'Phagocytes engulf and destroy invading pathogens', 'Lymphocytes produce specific antibodies and memory cells', 'Vaccination stimulates active immunity, preventing outbreaks of diseases such as measles and reducing child mortality'] },
  { type: 'essay', text: 'Discuss how human activities can disrupt the balance of an ecosystem, using examples relevant to Rwanda.', topic: 'Ecology',
    rubric: ['Deforestation reduces habitats and biodiversity', 'Overfishing/overharvesting disrupts food chains and species populations', 'Pollution from industries and agriculture harms aquatic and terrestrial organisms', 'Conservation measures such as national parks and reforestation help restore ecological balance'] },
];
