import { BankItem, mcq } from './types';

export const CHEMISTRY_ITEMS: BankItem[] = [
  mcq('What is the number of moles of NaOH present in 250 cm³ of a 2 mol/dm³ solution?', 'Mole Concept', ['0.25 mol', '0.5 mol', '1.0 mol', '2.0 mol'], 1),
  mcq('An acid is best defined as a substance that', 'Acids and Bases', ['Accepts protons in solution', 'Donates protons in solution', 'Accepts hydroxide ions', 'Turns litmus blue'], 1),
  mcq('In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, the substance oxidised is', 'Redox Reactions', ['Cu²⁺', 'Zn', 'SO₄²⁻', 'Cu'], 1),
  mcq('Which factor does NOT increase the rate of a chemical reaction?', 'Rates of Reaction', ['Increasing temperature', 'Increasing concentration', 'Adding a catalyst', 'Decreasing surface area'], 3),
  mcq('For the equilibrium N₂(g) + 3H₂(g) ⇌ 2NH₃(g), increasing pressure will', 'Chemical Equilibrium', ['Shift equilibrium to the left', 'Shift equilibrium to the right', 'Have no effect on equilibrium', 'Stop the reaction completely'], 1),
  mcq('The type of bond formed when electrons are transferred from a metal atom to a non-metal atom is', 'Bonding', ['Covalent bond', 'Metallic bond', 'Ionic bond', 'Hydrogen bond'], 2),
  mcq('In an acid-base titration, phenolphthalein indicator turns pink in', 'Titration', ['Acidic solution', 'Neutral solution', 'Basic solution', 'Any solution'], 2),
  mcq('The general formula for alkenes is', 'Organic Chemistry', ['CₙH₂ₙ₊₂', 'CₙH₂ₙ', 'CₙH₂ₙ₋₂', 'CₙHₙ'], 1),
  mcq('Across a period in the periodic table from left to right, atomic radius generally', 'Periodicity', ['Increases', 'Decreases', 'Remains constant', 'Increases then decreases'], 1),
  mcq('During the electrolysis of molten lead(II) bromide, lead metal is deposited at the', 'Electrolysis', ['Anode', 'Cathode', 'Salt bridge', 'Electrolyte surface'], 1),
  mcq('A reaction that releases heat energy to the surroundings is called', 'Energetics', ['Endothermic', 'Exothermic', 'Isothermal', 'Adiabatic'], 1),
  mcq('The Haber process is used industrially to manufacture', 'Industrial Chemistry', ['Sulphuric acid', 'Ammonia', 'Sodium hydroxide', 'Nitric acid'], 1),

  { type: 'true_false', text: 'One mole of any gas occupies 22.4 dm³ at standard temperature and pressure.', topic: 'Mole Concept', answer: 'True' },
  { type: 'true_false', text: 'A strong acid is one that is highly concentrated.', topic: 'Acids and Bases', answer: 'False' },
  { type: 'true_false', text: 'Oxidation involves the loss of electrons by a substance.', topic: 'Redox Reactions', answer: 'True' },
  { type: 'true_false', text: 'Catalysts are consumed during a chemical reaction.', topic: 'Rates of Reaction', answer: 'False' },
  { type: 'true_false', text: 'Ionic compounds generally have high melting and boiling points.', topic: 'Bonding', answer: 'True' },
  { type: 'true_false', text: 'Electrolysis of an aqueous solution always deposits the pure metal at the cathode regardless of reactivity.', topic: 'Electrolysis', answer: 'False' },

  { type: 'matching', text: 'Match each term in Column A with its correct description in Column B.', topic: 'Acids and Bases',
    pairs: [
      { left: 'Acid', right: 'A substance that donates hydrogen ions (protons) in solution' },
      { left: 'Base', right: 'A substance that accepts hydrogen ions in solution' },
      { left: 'Salt', right: 'A compound formed when an acid reacts with a base' },
      { left: 'Indicator', right: 'A substance that changes colour depending on pH' },
      { left: 'Neutralisation', right: 'Reaction between an acid and a base to form salt and water' },
    ] },
  { type: 'matching', text: 'Match each organic compound family in Column A with its characteristic functional group in Column B.', topic: 'Organic Chemistry',
    pairs: [
      { left: 'Alkanol', right: '-OH (hydroxyl group)' },
      { left: 'Alkanoic acid', right: '-COOH (carboxyl group)' },
      { left: 'Alkanal', right: '-CHO (aldehyde group)' },
      { left: 'Alkanone', right: '>C=O (ketone group)' },
    ] },
  { type: 'matching', text: 'Match each apparatus/technique in Column A with its correct use in Column B.', topic: 'Titration',
    pairs: [
      { left: 'Burette', right: 'Delivers a measured variable volume of a solution accurately' },
      { left: 'Pipette', right: 'Delivers a fixed, precise volume of a solution' },
      { left: 'Conical flask', right: 'Holds the solution being titrated during swirling' },
      { left: 'White tile', right: 'Placed under the flask to help observe the colour change clearly' },
      { left: 'Retort stand', right: 'Holds the burette firmly in an upright position' },
    ] },

  { type: 'fill_blank', text: 'The number of moles of a substance is calculated by dividing its mass by its ______.', topic: 'Mole Concept', answer: 'molar mass' },
  { type: 'fill_blank', text: 'A substance that speeds up a chemical reaction without being used up is called a ______.', topic: 'Rates of Reaction', answer: 'catalyst' },
  { type: 'fill_blank', text: 'The process by which an electric current is passed through a molten or aqueous compound to bring about a chemical change is called ______.', topic: 'Electrolysis', answer: 'electrolysis' },
  { type: 'fill_blank', text: 'Elements in the periodic table are arranged in order of increasing ______.', topic: 'Periodicity', answer: 'atomic number' },

  { type: 'short_answer', text: 'Calculate the number of moles of CO₂ produced when 5.6 g of calcium carbonate (CaCO₃, Mr = 100) decomposes completely.', topic: 'Mole Concept',
    answer: 'Moles of CaCO₃ = 5.6/100 = 0.056 mol. Since CaCO₃ → CaO + CO₂ (1:1 ratio), moles of CO₂ produced = 0.056 mol.',
    rubric: ['Correct formula: moles = mass/molar mass', 'Correct calculation of moles of CaCO₃ (0.056 mol)', 'Correct mole ratio identified (1:1)', 'Correct final answer with unit (0.056 mol CO₂)'] },
  { type: 'short_answer', text: 'State three factors that affect the rate of a chemical reaction and explain how each affects the rate.', topic: 'Rates of Reaction',
    answer: 'Temperature: increasing it gives particles more kinetic energy, causing more frequent and successful collisions. Concentration: increasing it raises the frequency of collisions between reacting particles. Surface area: increasing it (smaller particle size) exposes more particles to reaction, increasing collision frequency.',
    rubric: ['Temperature increases collision frequency and energy', 'Concentration increases collision frequency', 'Surface area increases exposed reacting particles', 'Catalyst provides an alternative pathway of lower activation energy'] },
  { type: 'short_answer', text: 'Explain why sodium chloride conducts electricity when molten or dissolved in water but not when solid.', topic: 'Electrolysis',
    answer: 'In the solid state, the ions are held tightly in a fixed lattice and cannot move freely, so there are no mobile charge carriers. When molten or dissolved in water, the lattice breaks down and the ions become free to move, allowing them to carry electric charge through the liquid.',
    rubric: ['Solid: ions fixed in lattice, cannot move', 'No mobile charge carriers in solid state', 'Molten/dissolved: ions become free/mobile', 'Free ions carry charge, enabling conductivity'] },
  { type: 'short_answer', text: 'Distinguish between exothermic and endothermic reactions, giving one example of each.', topic: 'Energetics',
    answer: 'An exothermic reaction releases heat energy to the surroundings and the temperature of the surroundings rises, e.g. combustion of methane. An endothermic reaction absorbs heat energy from the surroundings and the temperature falls, e.g. the reaction between citric acid and sodium hydrogen carbonate.',
    rubric: ['Exothermic releases heat, temperature rises', 'Correct example of exothermic reaction', 'Endothermic absorbs heat, temperature falls', 'Correct example of endothermic reaction'] },
  { type: 'short_answer', text: 'State three uses of sulphuric acid in industry.', topic: 'Industrial Chemistry',
    answer: 'Manufacture of fertilisers, manufacture of detergents, use as an electrolyte in car batteries, manufacture of paints and pigments, in petroleum refining.',
    rubric: ['Manufacture of fertilisers', 'Manufacture of detergents/paints', 'Electrolyte in lead-acid car batteries', 'Use in petroleum refining/dye manufacture'] },
  { type: 'short_answer', text: 'Explain why the boiling point of alkanes increases with increasing molecular size.', topic: 'Organic Chemistry',
    answer: 'As molecular size increases, the number of electrons in the molecule increases, strengthening the van der Waals forces of attraction between molecules, which requires more energy to overcome, thus raising the boiling point.',
    rubric: ['Larger molecules have more electrons', 'Stronger van der Waals forces between molecules', 'More energy needed to overcome intermolecular forces', 'Correct conclusion: boiling point increases with chain length'] },

  { type: 'structured', text: 'Students at a school in Musanze District carried out an acid-base titration to determine the concentration of a hydrochloric acid solution using 25.0 cm³ of 0.1 mol/dm³ sodium hydroxide and phenolphthalein indicator.',
    topic: 'Titration',
    parts: [
      { text: 'State the colour change observed at the end point of this titration.', answer: 'The solution changes from pink to colourless as the acid is added to the alkali.' },
      { text: 'Write a balanced chemical equation for the reaction between hydrochloric acid and sodium hydroxide.', answer: 'HCl(aq) + NaOH(aq) → NaCl(aq) + H₂O(l)' },
      { text: 'It was found that 20.0 cm³ of the hydrochloric acid was required to neutralise the sodium hydroxide.',
        parts: [
          { text: 'Calculate the number of moles of NaOH used.', answer: 'Moles = concentration × volume = 0.1 × (25.0/1000) = 0.0025 mol.' },
          { text: 'Calculate the concentration of the hydrochloric acid in mol/dm³.', answer: 'Since the mole ratio is 1:1, moles of HCl = 0.0025 mol; concentration = 0.0025/(20.0/1000) = 0.125 mol/dm³.' },
        ] },
    ] },
  { type: 'structured', text: 'A group of students in Rubavu District set up an experiment to study the electrolysis of copper(II) sulphate solution using copper electrodes, as part of a lesson on electroplating.',
    topic: 'Electrolysis',
    parts: [
      { text: 'Name the process by which copper is deposited onto an object using electrolysis.', answer: 'Electroplating.' },
      { text: 'Explain what happens at the cathode during this electrolysis.', answer: 'Copper(II) ions (Cu²⁺) migrate to the cathode where they gain electrons (are reduced) and are deposited as copper metal: Cu²⁺ + 2e⁻ → Cu.' },
      { text: 'The students also examined the anode during the process.',
        parts: [
          { text: 'State what happens to the copper anode during electrolysis.', answer: 'The copper anode dissolves, releasing Cu²⁺ ions into solution and losing electrons: Cu → Cu²⁺ + 2e⁻.' },
          { text: 'Explain why the mass of the anode decreases while the mass of the cathode increases.', answer: 'Copper atoms at the anode are oxidised and dissolve into solution as ions, decreasing its mass, while Cu²⁺ ions in solution are reduced and deposited on the cathode, increasing its mass.' },
        ] },
    ] },
  { type: 'structured', text: 'During a chemistry practical at a school in Huye District, students investigated the effect of concentration on the rate of reaction between dilute hydrochloric acid and marble chips (calcium carbonate) by measuring the volume of gas produced over time.',
    topic: 'Rates of Reaction',
    parts: [
      { text: 'Name the gas produced in this reaction.', answer: 'Carbon dioxide gas.' },
      { text: 'Explain why increasing the concentration of hydrochloric acid increases the rate of reaction.', answer: 'A higher concentration means there are more acid particles per unit volume, increasing the frequency of collisions between acid particles and the marble chips, resulting in a faster rate of reaction.' },
      { text: 'The students then repeated the experiment using powdered marble instead of chips.',
        parts: [
          { text: 'State the expected effect on the rate of reaction.', answer: 'The rate of reaction would increase.' },
          { text: 'Explain this expected effect.', answer: 'Powdered marble has a much greater surface area exposed to the acid, increasing the frequency of collisions between reacting particles, thus increasing the rate of reaction.' },
        ] },
    ] },
  { type: 'structured', text: 'A teacher in Nyagatare District demonstrated the reactivity series to students by placing strips of zinc, copper and magnesium into separate test tubes containing dilute sulphuric acid.',
    topic: 'Redox Reactions',
    parts: [
      { text: 'State which of the three metals produced no visible reaction with the dilute sulphuric acid.', answer: 'Copper.' },
      { text: 'Write the ionic half-equation for the oxidation of magnesium in this reaction.', answer: 'Mg → Mg²⁺ + 2e⁻' },
      { text: 'The teacher then asked the students to explain the reaction in terms of electron transfer.',
        parts: [
          { text: 'State which species is reduced when zinc reacts with dilute sulphuric acid.', answer: 'Hydrogen ions (H⁺) are reduced.' },
          { text: 'Write the ionic half-equation for this reduction.', answer: '2H⁺ + 2e⁻ → H₂' },
        ] },
    ] },

  { type: 'essay', text: 'Discuss the industrial manufacture of ammonia by the Haber process, including the conditions used and how they are chosen to maximise yield and rate.', topic: 'Industrial Chemistry',
    rubric: ['Reactants nitrogen and hydrogen combined under the equilibrium N₂ + 3H₂ ⇌ 2NH₃', 'Moderate temperature (about 450°C) balances yield and reaction rate', 'High pressure (about 200 atm) favours the forward reaction, which reduces gas moles', 'An iron catalyst is used to increase the rate of reaction without shifting equilibrium'] },
  { type: 'essay', text: 'Discuss the trend in reactivity of Group I (alkali) metals down the group, relating it to their atomic structure.', topic: 'Periodicity',
    rubric: ['Reactivity increases down the group', 'Atomic radius increases down the group due to additional electron shells', 'Outer electron becomes further from the nucleus, reducing nuclear attraction', 'Outer electron is more easily lost, so the metal reacts more readily'] },
  { type: 'essay', text: 'Discuss the environmental and economic importance of proper disposal and recycling of chemical waste, with reference to industries in Rwanda.', topic: 'Industrial Chemistry',
    rubric: ['Prevents pollution of water bodies such as Lake Kivu and rivers', 'Reduces harm to human health from toxic chemicals', 'Recycling recovers valuable materials, reducing production costs', 'Supports sustainable industrial growth and compliance with environmental regulations'] },
];
