import { BankItem, mcq } from './types';

export const ENGLISH_ITEMS: BankItem[] = [
  mcq('Choose the word that is a synonym of "abundant".', 'Vocabulary: Synonyms', ['Scarce', 'Plentiful', 'Fragile', 'Distant'], 1),
  mcq('Identify the correctly punctuated sentence.', 'Punctuation', ['Uwera bought bread milk and sugar.', 'Uwera bought bread, milk, and sugar.', 'Uwera bought bread, milk and, sugar.', 'Uwera bought, bread milk and sugar.'], 1),
  mcq('Select the sentence written in the passive voice.', 'Grammar: Active and Passive Voice', ['Mugisha repaired the motorcycle.', 'The motorcycle was repaired by Mugisha.', 'Mugisha is repairing the motorcycle.', 'Mugisha will repair the motorcycle.'], 1),
  mcq('Choose the correct reported speech for: Keza said, "I am tired."', 'Grammar: Reported Speech', ['Keza said that she is tired.', 'Keza said that she was tired.', 'Keza says that she was tired.', 'Keza said that I was tired.'], 1),
  mcq('Which literary device is used in "The wind whispered through the trees"?', 'Literary Devices', ['Simile', 'Personification', 'Hyperbole', 'Alliteration'], 1),
  mcq('Choose the phrasal verb that means "to postpone".', 'Vocabulary: Phrasal Verbs', ['Put off', 'Put on', 'Put up', 'Put out'], 0),
  mcq('Select the correct conditional sentence.', 'Grammar: Conditionals', ['If it rains, I will stayed home.', 'If it rains, I stay home.', 'If it rains, I will stay home.', 'If it will rain, I stay home.'], 2),
  mcq('Identify the noun clause in: "What she said surprised everyone."', 'Grammar: Clauses', ['She said', 'Surprised everyone', 'What she said', 'Everyone surprised'], 2),
  mcq('Choose the antonym of "generous".', 'Vocabulary: Antonyms', ['Stingy', 'Kind', 'Wealthy', 'Polite'], 0),
  mcq('Which sentence shows correct subject-verb concord?', 'Grammar: Concord', ['The list of items are on the table.', 'The list of items is on the table.', 'The list of items were on the table.', 'The list of items be on the table.'], 1),
  mcq('In a letter of complaint, which register is most appropriate?', 'Register and Formal Writing', ['Casual and humorous', 'Formal and polite', 'Slang and informal', 'Aggressive and rude'], 1),
  mcq('Select the correct form: "By next year, she ______ her studies."', 'Grammar: Tenses', ['will complete', 'will have completed', 'completes', 'is completing'], 1),
  { type: 'true_false', text: 'A metaphor makes a direct comparison between two unlike things without using "like" or "as".', topic: 'Literary Devices', answer: 'True' },
  { type: 'true_false', text: 'The passive voice always requires the auxiliary verb "have".', topic: 'Grammar: Active and Passive Voice', answer: 'False' },
  { type: 'true_false', text: 'A synonym is a word that means the opposite of another word.', topic: 'Vocabulary: Synonyms', answer: 'False' },
  { type: 'true_false', text: 'Formal letters should end with a complimentary close such as "Yours faithfully".', topic: 'Register and Formal Writing', answer: 'True' },
  { type: 'true_false', text: 'A comma splice occurs when two independent clauses are joined only by a comma.', topic: 'Punctuation', answer: 'True' },
  { type: 'true_false', text: 'Reported speech never changes the tense of the original statement.', topic: 'Grammar: Reported Speech', answer: 'False' },
  {
    type: 'matching',
    text: 'Match each literary term with its correct definition.',
    topic: 'Literary Devices',
    pairs: [
      { left: 'Simile', right: 'A comparison using "like" or "as"' },
      { left: 'Alliteration', right: 'Repetition of initial consonant sounds' },
      { left: 'Irony', right: 'A contrast between expectation and reality' },
      { left: 'Onomatopoeia', right: 'A word that imitates a sound' },
      { left: 'Hyperbole', right: 'An exaggerated statement not meant literally' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each word class with its correct example.',
    topic: 'Grammar: Word Classes',
    pairs: [
      { left: 'Noun', right: 'Rubavu' },
      { left: 'Adjective', right: 'Beautiful' },
      { left: 'Adverb', right: 'Quickly' },
      { left: 'Preposition', right: 'Beside' },
      { left: 'Conjunction', right: 'Although' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each type of writing with its main purpose.',
    topic: 'Composition Skills',
    pairs: [
      { left: 'Narrative essay', right: 'To tell a story' },
      { left: 'Argumentative essay', right: 'To persuade the reader of a viewpoint' },
      { left: 'Descriptive essay', right: 'To create a vivid picture using details' },
      { left: 'Formal letter', right: 'To communicate officially with a person or institution' },
    ],
  },
  { type: 'fill_blank', text: 'She ______ (teach) here since 2019.', topic: 'Grammar: Tenses', answer: 'has been teaching' },
  { type: 'fill_blank', text: 'The report ______ (write) by the committee before the meeting started.', topic: 'Grammar: Active and Passive Voice', answer: 'had been written' },
  { type: 'fill_blank', text: 'If she ______ (study) harder, she would have passed the examination.', topic: 'Grammar: Conditionals', answer: 'had studied' },
  { type: 'fill_blank', text: 'The word "meticulous" means very careful and ______.', topic: 'Vocabulary', answer: 'precise' },
  {
    type: 'short_answer',
    text: 'Explain the difference between a simile and a metaphor, giving one example of each.',
    topic: 'Literary Devices',
    answer: 'A simile compares two unlike things using "like" or "as" (e.g., "as brave as a lion"), while a metaphor states that one thing is another without using "like" or "as" (e.g., "he is a lion in battle").',
    rubric: ['Correct definition of simile', 'Correct definition of metaphor', 'Valid example of simile', 'Valid example of metaphor', 'Clarity of expression'],
  },
  {
    type: 'short_answer',
    text: 'State three features of a formal letter.',
    topic: 'Register and Formal Writing',
    answer: 'A formal letter should have: the sender\'s and receiver\'s addresses, a formal salutation (e.g., "Dear Sir/Madam"), a clear and polite tone, and a formal complimentary close (e.g., "Yours faithfully").',
    rubric: ['Address included', 'Formal salutation', 'Polite/formal tone', 'Appropriate complimentary close'],
  },
  {
    type: 'short_answer',
    text: 'Rewrite the sentence in reported speech: Mugisha said, "I will visit Kigali tomorrow."',
    topic: 'Grammar: Reported Speech',
    answer: 'Mugisha said that he would visit Kigali the following day.',
    rubric: ['Correct tense shift', 'Correct pronoun change', 'Correct time expression change'],
  },
  {
    type: 'short_answer',
    text: 'Explain the meaning of the phrasal verb "look into" and use it in a sentence.',
    topic: 'Vocabulary: Phrasal Verbs',
    answer: '"Look into" means to investigate or examine something closely. Example: The police decided to look into the theft reported at the market in Gisenyi.',
    rubric: ['Correct meaning', 'Grammatically correct sentence', 'Sentence demonstrates meaning'],
  },
  {
    type: 'short_answer',
    text: 'Identify and correct the error in the sentence: "Each of the students have submitted their assignment."',
    topic: 'Grammar: Concord',
    answer: 'The error is subject-verb agreement; "have" should be "has" because "each" is singular: "Each of the students has submitted their assignment."',
    rubric: ['Error correctly identified', 'Correct replacement given', 'Explanation of concord rule'],
  },
  {
    type: 'short_answer',
    text: 'State three punctuation marks used to separate items in a list and briefly explain their use.',
    topic: 'Punctuation',
    answer: 'Commas separate individual items in a simple list; semicolons separate items that themselves contain commas; and a colon introduces the list itself.',
    rubric: ['Comma explained', 'Semicolon explained', 'Colon explained'],
  },
  {
    type: 'structured',
    text: 'Read the following extract: "Uwera walked slowly through the market in Rubavu, her basket empty, her heart heavier than the clouds above her." Answer the questions that follow.',
    topic: 'Literary Devices',
    parts: [
      { text: 'Identify the figure of speech used in "her heart heavier than the clouds above her" and explain its effect.', answer: 'This is a simile comparing Uwera\'s heart to the clouds; it emphasises her deep sadness and creates a vivid, sombre mood.' },
      { text: 'Describe the mood created in this extract.', answer: 'The mood is sorrowful and melancholic, reflecting Uwera\'s disappointment and emotional heaviness.' },
      { text: 'Answer the following about the extract.', answer: '', parts: [
        { text: 'What does the word "empty" suggest about Uwera\'s situation?', answer: 'It suggests that she was unable to buy anything, implying poverty or lack of money.' },
        { text: 'Suggest an alternative title for this extract.', answer: 'A suitable title could be "A Heavy Heart" or "Empty Basket, Heavy Heart".' },
      ] },
    ],
  },
  {
    type: 'structured',
    text: 'A student wrote the following sentence in an examination: "The teacher explain that student who work hard will succeeded." Answer the questions based on this sentence.',
    topic: 'Grammar: Tenses and Concord',
    parts: [
      { text: 'Identify two grammatical errors in the sentence.', answer: 'The verb "explain" should be "explained" (past tense), and "succeeded" should be "succeed" (base form after "will").' },
      { text: 'Rewrite the sentence correctly.', answer: 'The teacher explained that students who work hard will succeed.' },
      { text: 'Answer the following about the corrected sentence.', answer: '', parts: [
        { text: 'Identify the tense used in the main clause.', answer: 'The simple past tense is used in the main clause ("explained").' },
        { text: 'Identify the tense used in the subordinate clause referring to the future.', answer: 'The simple future tense is used ("will succeed").' },
      ] },
    ],
  },
  {
    type: 'structured',
    text: 'Keza wants to write a formal letter to the Mayor of Rubavu District requesting support for a youth cooperative project. Answer the questions below.',
    topic: 'Register and Formal Writing',
    parts: [
      { text: 'State the appropriate salutation Keza should use if she does not know the Mayor\'s name.', answer: 'Dear Sir/Madam,' },
      { text: 'State the appropriate complimentary close for this letter.', answer: 'Yours faithfully,' },
      { text: 'Answer the following about the letter\'s structure.', answer: '', parts: [
        { text: 'State one item that should appear at the top right of the letter.', answer: 'The sender\'s address (Keza\'s address).' },
        { text: 'State the tone that should be maintained throughout the letter.', answer: 'A formal and respectful tone.' },
      ] },
    ],
  },
  {
    type: 'structured',
    text: 'Consider the sentence: "Although the road to Musanze was under construction, the driver managed to arrive on time." Answer the questions that follow.',
    topic: 'Grammar: Clauses',
    parts: [
      { text: 'Identify the subordinate clause in the sentence.', answer: '"Although the road to Musanze was under construction" is the subordinate clause.' },
      { text: 'State the type of clause identified above.', answer: 'It is an adverbial clause of concession.' },
      { text: 'Answer the following about the sentence.', answer: '', parts: [
        { text: 'Identify the main clause in the sentence.', answer: '"The driver managed to arrive on time" is the main clause.' },
        { text: 'Rewrite the sentence beginning with "Despite".', answer: 'Despite the construction on the road to Musanze, the driver managed to arrive on time.' },
      ] },
    ],
  },
  {
    type: 'essay',
    text: 'Write a composition of about 400 words on the topic: "The Importance of Vocational Education in Rwanda\'s Development."',
    topic: 'Composition Writing',
    rubric: ['Clear introduction stating the thesis', 'Well-developed body paragraphs with relevant examples', 'Correct grammar, spelling, and punctuation', 'Logical conclusion summarising the argument'],
  },
  {
    type: 'essay',
    text: 'Write a formal letter to the Director of your school requesting permission to organise a debate club at your school.',
    topic: 'Formal Letter Writing',
    rubric: ['Correct formal letter format (addresses, date, salutation, close)', 'Clear statement of purpose', 'Polite and formal register throughout', 'Logical organisation of ideas'],
  },
  {
    type: 'essay',
    text: 'Some people believe that technology has made students lazy, while others believe it has improved learning. Discuss both views and give your own opinion.',
    topic: 'Argumentative Writing',
    rubric: ['Balanced discussion of both viewpoints', 'Use of relevant, specific examples', 'Clear personal opinion supported with reasons', 'Coherent structure and correct language use'],
  },
];
