import { BankItem, mcq } from './types';

export const ENTREPRENEURSHIP_ITEMS: BankItem[] = [
  mcq('Which of the following best defines an entrepreneur?', 'Entrepreneurship Concepts', ['A person who works only for the government', 'A person who identifies opportunities and organises resources to start a business', 'A person who saves money in a bank', 'A person employed by a large company'], 1),
  mcq('Which form of business ownership is owned and controlled by one person?', 'Forms of Business Ownership', ['Partnership', 'Cooperative', 'Sole proprietorship', 'Public limited company'], 2),
  mcq('Which document is issued to a customer as proof of payment for goods?', 'Business Documents', ['Invoice', 'Receipt', 'Local purchase order', 'Quotation'], 1),
  mcq('The point at which total revenue equals total costs is called the:', 'Break-even Analysis', ['Profit margin', 'Break-even point', 'Fixed cost point', 'Net income point'], 1),
  mcq('Dividing a market into groups of buyers with similar needs is called:', 'Marketing and Market Segmentation', ['Market saturation', 'Market segmentation', 'Market monopoly', 'Market equilibrium'], 1),
  mcq('Which of the following is a fixed cost for a small business?', 'Costing', ['Cost of raw materials', 'Monthly rent for premises', 'Delivery fuel per trip', 'Packaging materials'], 1),
  mcq('Which institution in Rwanda is primarily responsible for tax collection?', 'Taxation', ['BNR', 'RRA', 'RDB', 'BDF'], 1),
  mcq('A group of people who voluntarily join together to meet common economic needs through a jointly owned enterprise is called a:', 'Forms of Business Ownership', ['Sole trader', 'Cooperative', 'Franchise', 'Partnership'], 1),
  mcq('Which record shows all money received and paid out by a business?', 'Financial Records', ['Balance sheet', 'Cash book', 'Trial balance', 'Stock card'], 1),
  mcq('Which of the following is an example of an entrepreneurial competence?', 'Entrepreneurship Competences', ['Fear of taking risks', 'Persistence in overcoming challenges', 'Avoiding new ideas', 'Dependence on others for decisions'], 1),
  mcq('A cooperative that helps its members save money and access loans is called a:', 'Savings and Credit', ['SACCO', 'SME', 'NGO', 'MFI headquarters'], 0),
  mcq('Acting with honesty, fairness, and respect for customers in business is known as:', 'Business Ethics', ['Business ethics', 'Market segmentation', 'Break-even analysis', 'Capital budgeting'], 0),
  { type: 'true_false', text: 'A business plan helps an entrepreneur to clarify goals and attract investors.', topic: 'Business Planning', answer: 'True' },
  { type: 'true_false', text: 'In a partnership, only one partner is legally liable for the debts of the business.', topic: 'Forms of Business Ownership', answer: 'False' },
  { type: 'true_false', text: 'Fixed costs remain constant regardless of the level of output produced.', topic: 'Costing', answer: 'True' },
  { type: 'true_false', text: 'An invoice and a receipt serve exactly the same purpose in a business transaction.', topic: 'Business Documents', answer: 'False' },
  { type: 'true_false', text: 'SMEs play a significant role in job creation and poverty reduction in Rwanda.', topic: 'SMEs in Rwanda', answer: 'True' },
  { type: 'true_false', text: 'Paying taxes is optional for registered businesses in Rwanda.', topic: 'Taxation', answer: 'False' },
  {
    type: 'matching',
    text: 'Match each business document with its correct use.',
    topic: 'Business Documents',
    pairs: [
      { left: 'Invoice', right: 'Requests payment for goods or services supplied' },
      { left: 'Receipt', right: 'Confirms that payment has been received' },
      { left: 'Local Purchase Order', right: 'Used by a buyer to formally order goods from a supplier' },
      { left: 'Delivery note', right: 'Confirms goods delivered match the order' },
      { left: 'Quotation', right: 'States the estimated price of goods or services before an order is made' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each business concept with its correct definition.',
    topic: 'Entrepreneurship Concepts',
    pairs: [
      { left: 'Capital', right: 'Money or assets used to start or run a business' },
      { left: 'Market', right: 'A place or system where buyers and sellers exchange goods' },
      { left: 'Profit', right: 'The excess of revenue over total costs' },
      { left: 'Risk', right: 'The possibility of loss or failure in a business venture' },
      { left: 'Innovation', right: 'Introducing new ideas, products, or methods' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each form of business ownership with its correct feature.',
    topic: 'Forms of Business Ownership',
    pairs: [
      { left: 'Sole proprietorship', right: 'Owned and managed by one individual with unlimited liability' },
      { left: 'Partnership', right: 'Owned by two or more people who share profits and liability' },
      { left: 'Cooperative', right: 'Owned and controlled democratically by its members' },
      { left: 'Limited company', right: 'Owned by shareholders with liability limited to their shares' },
    ],
  },
  { type: 'fill_blank', text: 'The document that lists goods sold on credit and requests payment is called an ______.', topic: 'Business Documents', answer: 'invoice' },
  { type: 'fill_blank', text: 'The total cost of a business is the sum of its fixed costs and its ______ costs.', topic: 'Costing', answer: 'variable' },
  { type: 'fill_blank', text: 'A business owned by shareholders whose liability is limited to the amount they invested is called a ______ company.', topic: 'Forms of Business Ownership', answer: 'limited' },
  { type: 'fill_blank', text: 'In Rwanda, small and medium enterprises are commonly abbreviated as ______.', topic: 'SMEs in Rwanda', answer: 'SMEs' },
  {
    type: 'short_answer',
    text: 'State three characteristics of a successful entrepreneur.',
    topic: 'Entrepreneurship Competences',
    answer: 'A successful entrepreneur is innovative, self-confident, willing to take calculated risks, persistent when facing challenges, and able to identify and exploit business opportunities.',
    rubric: ['Innovativeness', 'Risk-taking ability', 'Persistence/self-confidence', 'Opportunity identification', 'Clarity of expression'],
  },
  {
    type: 'short_answer',
    text: 'Explain the difference between fixed costs and variable costs, giving one example of each.',
    topic: 'Costing',
    answer: 'Fixed costs remain constant regardless of output, e.g., rent; variable costs change with the level of output, e.g., cost of raw materials.',
    rubric: ['Correct definition of fixed cost', 'Correct definition of variable cost', 'Valid example of each', 'Clear distinction shown'],
  },
  {
    type: 'short_answer',
    text: 'State three advantages of forming a cooperative in a Rwandan community.',
    topic: 'Forms of Business Ownership',
    answer: 'Cooperatives allow members to pool resources, access credit more easily, share risks and responsibilities, benefit from bulk buying and selling, and gain a stronger bargaining position.',
    rubric: ['Pooling of resources', 'Easier access to credit', 'Shared risk/responsibility', 'Improved bargaining power'],
  },
  {
    type: 'short_answer',
    text: 'Explain the term "market segmentation" and state one benefit to a business.',
    topic: 'Marketing and Market Segmentation',
    answer: 'Market segmentation is the process of dividing a market into distinct groups of customers with similar needs or characteristics. It benefits a business by allowing it to design products and marketing strategies that target each group more effectively.',
    rubric: ['Correct definition', 'Valid benefit stated', 'Clarity of explanation'],
  },
  {
    type: 'short_answer',
    text: 'State three reasons why keeping accurate financial records is important for a small business.',
    topic: 'Financial Records',
    answer: 'Accurate financial records help a business monitor profitability, control cash flow, make informed decisions, comply with tax obligations, and attract investors or lenders.',
    rubric: ['Monitoring profitability', 'Controlling cash flow', 'Supporting decision-making', 'Compliance with tax requirements'],
  },
  {
    type: 'short_answer',
    text: 'Explain two ways in which paying taxes benefits the Rwandan economy.',
    topic: 'Taxation',
    answer: 'Taxes provide government revenue used to fund public services such as roads, schools, and hospitals, and they help redistribute wealth to support national development programmes.',
    rubric: ['Funding of public services explained', 'Contribution to national development explained'],
  },
  {
    type: 'structured',
    text: 'Mugisha runs a small tailoring business in Musanze. In a given month, his fixed costs (rent and salaries) amount to FRW 150,000, and each shirt he makes costs FRW 5,000 in materials and labour. He sells each shirt for FRW 8,000. Answer the questions that follow.',
    topic: 'Break-even Analysis',
    parts: [
      { text: 'Calculate the contribution margin per shirt.', answer: 'Contribution margin = Selling price − Variable cost = FRW 8,000 − FRW 5,000 = FRW 3,000 per shirt.' },
      { text: 'Calculate the number of shirts Mugisha must sell to break even.', answer: 'Break-even quantity = Fixed costs ÷ Contribution margin = FRW 150,000 ÷ FRW 3,000 = 50 shirts.' },
      { text: 'Answer the following about Mugisha\'s business.', answer: '', parts: [
        { text: 'Calculate Mugisha\'s total revenue if he sells 70 shirts in a month.', answer: 'Total revenue = 70 × FRW 8,000 = FRW 560,000.' },
        { text: 'Calculate Mugisha\'s profit if he sells 70 shirts in that month.', answer: 'Total cost = FRW 150,000 + (70 × FRW 5,000) = FRW 150,000 + FRW 350,000 = FRW 500,000. Profit = FRW 560,000 − FRW 500,000 = FRW 60,000.' },
      ] },
    ],
  },
  {
    type: 'structured',
    text: 'Uwera wants to start a poultry farming business in Rubavu District. She estimates she needs FRW 2,000,000 in start-up capital: FRW 800,000 for building a chicken coop, FRW 700,000 for buying chicks and feed, and FRW 500,000 as a reserve for unexpected expenses. Answer the questions that follow.',
    topic: 'Business Planning',
    parts: [
      { text: 'State two reasons why Uwera should prepare a business plan before starting her poultry business.', answer: 'A business plan helps Uwera clarify her business goals and strategies, and it can be used to convince banks or investors to provide the required financing.' },
      { text: 'Calculate the percentage of total start-up capital allocated to buying chicks and feed.', answer: 'Percentage = (FRW 700,000 ÷ FRW 2,000,000) × 100 = 35%.' },
      { text: 'Answer the following about Uwera\'s start-up capital.', answer: '', parts: [
        { text: 'Calculate the percentage of total capital allocated to the reserve fund.', answer: 'Percentage = (FRW 500,000 ÷ FRW 2,000,000) × 100 = 25%.' },
        { text: 'State one possible source of finance Uwera could use to raise this capital.', answer: 'She could obtain a loan from a SACCO or microfinance institution, or use personal savings.' },
      ] },
    ],
  },
  {
    type: 'structured',
    text: 'Keza owns a small retail shop in Gisenyi selling household goods. Last month, her total sales were FRW 1,200,000 and her total expenses (stock purchases, rent, and transport) were FRW 900,000. Answer the questions that follow.',
    topic: 'Financial Records',
    parts: [
      { text: 'Calculate Keza\'s net profit for the month.', answer: 'Net profit = Total sales − Total expenses = FRW 1,200,000 − FRW 900,000 = FRW 300,000.' },
      { text: 'State one financial record Keza should keep to track her daily cash transactions.', answer: 'Keza should keep a cash book to record all cash received and paid out daily.' },
      { text: 'Answer the following about Keza\'s shop records.', answer: '', parts: [
        { text: 'Calculate Keza\'s profit margin as a percentage of sales.', answer: 'Profit margin = (Net profit ÷ Sales) × 100 = (FRW 300,000 ÷ FRW 1,200,000) × 100 = 25%.' },
        { text: 'State one benefit of calculating profit margin regularly.', answer: 'It helps Keza monitor the efficiency and profitability of her business over time and make informed pricing decisions.' },
      ] },
    ],
  },
  {
    type: 'structured',
    text: 'Mugabo, an entrepreneur in Kigali, wants to register his growing carpentry workshop as a limited company instead of continuing as a sole proprietorship. Answer the questions that follow.',
    topic: 'Forms of Business Ownership',
    parts: [
      { text: 'State one advantage of a limited company over a sole proprietorship.', answer: 'A limited company offers limited liability, meaning Mugabo\'s personal assets are protected if the business fails, unlike a sole proprietorship.' },
      { text: 'State one disadvantage of converting to a limited company.', answer: 'A limited company faces more complex legal requirements and higher costs of registration and compliance than a sole proprietorship.' },
      { text: 'Answer the following about Mugabo\'s decision.', answer: '', parts: [
        { text: 'State one document Mugabo would need to register his limited company in Rwanda.', answer: 'He would need the company\'s memorandum and articles of association (or register with the Rwanda Development Board, RDB).' },
        { text: 'State one benefit limited company status could bring to Mugabo\'s access to finance.', answer: 'It could make it easier for Mugabo to raise capital by selling shares or attracting investors.' },
      ] },
    ],
  },
  {
    type: 'essay',
    text: 'Discuss the challenges faced by small and medium enterprises (SMEs) in Rwanda and suggest possible solutions.',
    topic: 'SMEs in Rwanda',
    rubric: ['Identification of relevant challenges (e.g., limited access to finance, low technical skills)', 'Explanation of how each challenge affects SMEs', 'Practical and relevant solutions proposed', 'Logical organisation and use of relevant Rwandan examples'],
  },
  {
    type: 'essay',
    text: 'Discuss the importance of business ethics in ensuring the long-term success of a business.',
    topic: 'Business Ethics',
    rubric: ['Clear explanation of the concept of business ethics', 'Discussion of at least three benefits of ethical practice', 'Use of relevant examples to support points', 'Well-organised argument with a clear conclusion'],
  },
  {
    type: 'essay',
    text: 'Discuss the role of savings and access to credit in promoting entrepreneurship among young people in Rwanda.',
    topic: 'Savings and Credit',
    rubric: ['Explanation of the role of savings in starting a business', 'Explanation of the role of credit/SACCOs in business growth', 'Reference to relevant Rwandan institutions or schemes', 'Balanced discussion with a reasoned conclusion'],
  },
];
