import { BankItem, mcq } from './types';

export const MATHEMATICS_ITEMS: BankItem[] = [
  mcq('Solve for x: 3x - 7 = 14.', 'Linear equations', ['x = 5', 'x = 7', 'x = 21/3', 'x = 3'], 1),
  mcq('If f(x) = x² - 4x + 3, find f(2).', 'Functions', ['-1', '1', '3', '0'], 0),
  mcq('The gradient of the line 2y = 4x + 6 is:', 'Coordinate geometry', ['4', '2', '6', '-2'], 1),
  mcq('Find the 5th term of the arithmetic sequence 3, 7, 11, 15, ...', 'Sequences', ['19', '17', '23', '21'], 0),
  mcq('Solve the quadratic equation x² - 5x + 6 = 0.', 'Quadratic equations', ['x = 2 or x = 3', 'x = -2 or x = -3', 'x = 1 or x = 6', 'x = 2 or x = -3'], 0),
  mcq('Evaluate log₁₀ 100.', 'Logarithms', ['1', '2', '10', '100'], 1),
  mcq('Find the derivative of y = 3x⁴ - 2x.', 'Calculus (differentiation)', ['12x³ - 2', '3x³ - 2', '12x³ - 2x', '4x³ - 2'], 0),
  mcq('The mean of the numbers 4, 6, 8, 10, 12 is:', 'Statistics (mean)', ['8', '7', '9', '10'], 0),
  mcq('A bag contains 5 red and 3 blue balls. What is the probability of drawing a red ball?', 'Probability', ['5/8', '3/8', '5/3', '1/8'], 0,),
  mcq('If vector a = (3, 4), find |a|.', 'Vectors', ['7', '5', '12', '25'], 1),
  mcq('sin 30° is equal to:', 'Trigonometry', ['1/2', '√3/2', '1', '√2/2'], 0),
  mcq('Find ∫2x dx.', 'Calculus (integration)', ['x² + c', '2x² + c', 'x²/2 + c', '2 + c'], 0),
  { type: 'true_false', text: 'The sum of the angles in a triangle is always 180°.', topic: 'Geometry', answer: 'True' },
  { type: 'true_false', text: 'The equation x² + 1 = 0 has real roots.', topic: 'Quadratic equations', answer: 'False' },
  { type: 'true_false', text: 'A function f(x) = 2x + 1 is a linear function.', topic: 'Functions', answer: 'True' },
  { type: 'true_false', text: 'The median of a data set is always equal to its mean.', topic: 'Statistics', answer: 'False' },
  { type: 'true_false', text: 'The derivative of a constant is zero.', topic: 'Calculus (differentiation)', answer: 'True' },
  { type: 'true_false', text: 'Parallel lines have different gradients.', topic: 'Coordinate geometry', answer: 'False' },
  {
    type: 'matching',
    text: 'Match each function with its derivative.',
    topic: 'Calculus (differentiation)',
    pairs: [
      { left: 'y = x³', right: 'dy/dx = 3x²' },
      { left: 'y = 5x', right: 'dy/dx = 5' },
      { left: 'y = sin x', right: 'dy/dx = cos x' },
      { left: 'y = x²', right: 'dy/dx = 2x' },
      { left: 'y = 7', right: 'dy/dx = 0' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each mathematical term with its correct definition.',
    topic: 'General mathematics terms',
    pairs: [
      { left: 'Prime number', right: 'A number with exactly two factors, 1 and itself' },
      { left: 'Median', right: 'The middle value of an ordered data set' },
      { left: 'Asymptote', right: 'A line that a curve approaches but never touches' },
      { left: 'Vector', right: 'A quantity with both magnitude and direction' },
      { left: 'Reciprocal', right: 'The multiplicative inverse of a number' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each trigonometric ratio at 60° with its value.',
    topic: 'Trigonometry',
    pairs: [
      { left: 'sin 60°', right: '√3/2' },
      { left: 'cos 60°', right: '1/2' },
      { left: 'tan 60°', right: '√3' },
      { left: 'sin 90°', right: '1' },
      { left: 'cos 0°', right: '1' },
    ],
  },
  { type: 'fill_blank', text: 'The formula for the nth term of an arithmetic sequence is Uₙ = a + (n - 1)______.', topic: 'Sequences', answer: 'd' },
  { type: 'fill_blank', text: 'The discriminant of a quadratic equation ax² + bx + c = 0 is given by ______.', topic: 'Quadratic equations', answer: 'b² - 4ac' },
  { type: 'fill_blank', text: 'The standard deviation is the ______ root of the variance.', topic: 'Statistics', answer: 'square' },
  { type: 'fill_blank', text: 'Two vectors are perpendicular if their dot product equals ______.', topic: 'Vectors', answer: '0' },
  {
    type: 'short_answer',
    text: 'A cooperative in Musanze sells irish potatoes. Solve the simultaneous equations: 2x + y = 11 and x - y = 1, where x and y represent bags sold by two members.',
    topic: 'Simultaneous equations',
    answer: 'Adding: 2x + y = 11, x - y = 1 → 3x = 12, x = 4. Substituting: 4 - y = 1, y = 3. So x = 4, y = 3.',
    rubric: ['Correctly sets up elimination (1 mark)', 'Solves for x = 4 (2 marks)', 'Solves for y = 3 (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'Find the equation of the straight line passing through the points (1, 2) and (3, 8).',
    topic: 'Coordinate geometry',
    answer: 'Gradient m = (8 - 2)/(3 - 1) = 6/2 = 3. Using y - 2 = 3(x - 1): y = 3x - 1.',
    rubric: ['Calculates gradient m = 3 (2 marks)', 'Applies point-gradient formula (1 mark)', 'Simplifies to y = 3x - 1 (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'Calculate the mean and standard deviation of the data set: 2, 4, 4, 6, 8.',
    topic: 'Statistics',
    answer: 'Mean = (2+4+4+6+8)/5 = 24/5 = 4.8. Deviations: -2.8, -0.8, -0.8, 1.2, 3.2. Squares: 7.84, 0.64, 0.64, 1.44, 10.24, sum = 20.8. Variance = 20.8/5 = 4.16. SD = √4.16 ≈ 2.04.',
    rubric: ['Correct mean = 4.8 (2 marks)', 'Correct variance calculation (2 marks)', 'Correct standard deviation ≈ 2.04 (1 mark)'],
  },
  {
    type: 'short_answer',
    text: 'A tin of milk cans is shaped like a box. Given that the probability of picking a defective can from a batch of 200 is 0.05, find the number of defective cans.',
    topic: 'Probability',
    answer: 'Number of defective cans = 0.05 × 200 = 10 cans.',
    rubric: ['Identifies correct formula (2 marks)', 'Correct substitution (1 mark)', 'Correct final answer = 10 (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'Differentiate y = 4x³ - 6x² + 2x - 5 and find dy/dx at x = 1.',
    topic: 'Calculus (differentiation)',
    answer: 'dy/dx = 12x² - 12x + 2. At x = 1: dy/dx = 12 - 12 + 2 = 2.',
    rubric: ['Correct differentiation (3 marks)', 'Correct substitution x = 1 (1 mark)', 'Correct final value = 2 (1 mark)'],
  },
  {
    type: 'short_answer',
    text: 'Given vectors a = (2, 3) and b = (-1, 4), find a + 2b and its magnitude.',
    topic: 'Vectors',
    answer: 'a + 2b = (2, 3) + (-2, 8) = (0, 11). Magnitude = √(0² + 11²) = √121 = 11.',
    rubric: ['Correctly doubles vector b (1 mark)', 'Correct vector sum = (0, 11) (2 marks)', 'Correct magnitude = 11 (2 marks)'],
  },
  {
    type: 'structured',
    text: 'A savings cooperative in Huye recorded the number of new members joining each month for six months: 12, 15, 18, 14, 20, 21.',
    topic: 'Statistics',
    parts: [
      { text: 'Calculate the mean number of new members per month.', answer: 'Mean = (12+15+18+14+20+21)/6 = 100/6 ≈ 16.7 members.' },
      { text: 'Calculate the median number of new members.', answer: 'Ordered: 12,14,15,18,20,21. Median = (15+18)/2 = 16.5 members.' },
      {
        text: 'The cooperative wants to compare variability.',
        parts: [
          { text: 'Find the range of the data.', answer: 'Range = 21 - 12 = 9 members.' },
          { text: 'State one advantage of using the range as a measure of spread.', answer: 'It is simple and quick to calculate, requiring only the highest and lowest values.' },
        ],
      },
    ],
  },
  {
    type: 'structured',
    text: 'A stone is dropped from a bridge over the Nyabarongo River, and its height above the water is given by h(t) = 45 - 5t², where h is in metres and t in seconds.',
    topic: 'Calculus and applications',
    parts: [
      { text: 'Find the height of the stone at t = 2 seconds.', answer: 'h(2) = 45 - 5(4) = 45 - 20 = 25 m.' },
      { text: 'Find the time taken for the stone to reach the water (h = 0).', answer: '45 - 5t² = 0 → t² = 9 → t = 3 seconds.' },
      {
        text: 'Consider the rate of change of height.',
        parts: [
          { text: 'Find dh/dt, the velocity function.', answer: 'dh/dt = -10t m/s.' },
          { text: 'Find the velocity of the stone at t = 3 seconds.', answer: 'dh/dt at t = 3 is -10(3) = -30 m/s (i.e. 30 m/s downward).' },
        ],
      },
    ],
  },
  {
    type: 'structured',
    text: 'A water tank in Nyagatare is being filled such that the volume V (in litres) after t minutes is V(t) = 20t + 3t².',
    topic: 'Calculus and algebra',
    parts: [
      { text: 'Find the volume in the tank after 5 minutes.', answer: 'V(5) = 20(5) + 3(25) = 100 + 75 = 175 litres.' },
      { text: 'Find dV/dt, the rate at which the tank is filling.', answer: 'dV/dt = 20 + 6t litres per minute.' },
      {
        text: 'The tank has a capacity of 500 litres.',
        parts: [
          { text: 'Find the rate of filling at t = 10 minutes.', answer: 'dV/dt at t=10 = 20 + 60 = 80 litres/minute.' },
          { text: 'Estimate whether the tank will be full before t = 15 minutes, showing your working.', answer: 'V(15) = 20(15) + 3(225) = 300 + 675 = 975 litres, which exceeds 500 litres, so the tank will be full before t = 15 minutes.' },
        ],
      },
    ],
  },
  {
    type: 'structured',
    text: 'A trader at Kimironko market records daily profit (in FRW thousands) modelled by P(x) = -2x² + 20x, where x is the number of baskets of tomatoes sold.',
    topic: 'Quadratic functions',
    parts: [
      { text: 'Find the profit when x = 4 baskets are sold.', answer: 'P(4) = -2(16) + 80 = -32 + 80 = 48, i.e. FRW 48,000.' },
      { text: 'Find the number of baskets that maximise profit.', answer: 'Maximum at x = -b/2a = -20/(2×-2) = 5 baskets.' },
      {
        text: 'The trader wants to know the break-even points.',
        parts: [
          { text: 'Solve P(x) = 0 to find the break-even values of x.', answer: '-2x² + 20x = 0 → -2x(x - 10) = 0 → x = 0 or x = 10.' },
          { text: 'Interpret the meaning of x = 10 in this context.', answer: 'At x = 10 baskets sold, the trader makes zero profit; beyond this the profit model becomes negative (a loss).' },
        ],
      },
    ],
  },
  {
    type: 'essay',
    text: 'Discuss the importance of statistics in decision-making for a farming cooperative in Rwanda, giving examples of measures of central tendency and dispersion that could be used.',
    topic: 'Statistics (application)',
    rubric: [
      'Explains the role of statistics in informed decision-making',
      'Describes at least one measure of central tendency (mean, median, or mode) with an example',
      'Describes at least one measure of dispersion (range, variance, or standard deviation) with an example',
      'Provides a relevant Rwandan cooperative context and draws a clear conclusion',
    ],
  },
  {
    type: 'essay',
    text: 'Investigate the relationship between differentiation and rates of change. Explain, with examples, how derivatives can be applied to real-life situations such as profit maximisation or motion.',
    topic: 'Calculus (application)',
    rubric: [
      'Correctly defines the derivative as a rate of change',
      'Gives a worked example involving motion (velocity/acceleration)',
      'Gives a worked example involving optimisation (e.g. maximum profit)',
      'Draws a logical, well-structured conclusion linking theory to application',
    ],
  },
  {
    type: 'essay',
    text: 'Discuss how probability theory can be used to make predictions in everyday life, such as weather forecasting or insurance in Rwanda.',
    topic: 'Probability (application)',
    rubric: [
      'Defines probability clearly with correct terminology',
      'Explains at least two real-life applications of probability',
      'Uses a suitable numerical example to illustrate a probability calculation',
      'Concludes with a reflection on the value of probability in planning and risk management',
    ],
  },
];
