import { BankItem, mcq } from './types';

export const PHYSICS_ITEMS: BankItem[] = [
  mcq('The SI unit of force is the:', 'Mechanics (forces)', ['Joule', 'Newton', 'Watt', 'Pascal'], 1),
  mcq('A car accelerates uniformly from 0 to 20 m/s in 4 seconds. Its acceleration is:', 'Mechanics (motion)', ['5 m/s²', '80 m/s²', '4 m/s²', '0.2 m/s²'], 0),
  mcq('Ohm\'s law states that:', 'Electricity', ['V = IR', 'P = IV', 'V = I/R', 'I = VR'], 0),
  mcq('The energy stored in a stretched spring is called:', 'Energy', ['Kinetic energy', 'Elastic potential energy', 'Thermal energy', 'Chemical energy'], 1),
  mcq('An object of mass 2 kg moving at 3 m/s has momentum of:', 'Momentum', ['6 kg·m/s', '1.5 kg·m/s', '5 kg·m/s', '3 kg·m/s'], 0),
  mcq('The speed of light in a vacuum is approximately:', 'Waves and optics', ['3 × 10⁸ m/s', '3 × 10⁶ m/s', '3 × 10⁵ m/s', '3 × 10⁴ m/s'], 0),
  mcq('Which instrument is used to measure atmospheric pressure?', 'Pressure', ['Thermometer', 'Barometer', 'Ammeter', 'Manometer'], 1),
  mcq('The process by which a radioactive nucleus emits an alpha particle is called:', 'Radioactivity', ['Fission', 'Fusion', 'Alpha decay', 'Beta decay'], 2),
  mcq('The unit of electrical resistance is the:', 'Electricity', ['Ampere', 'Volt', 'Ohm', 'Watt'], 2),
  mcq('When light passes from air into glass, it:', 'Waves and optics', ['Speeds up and bends away from normal', 'Slows down and bends towards normal', 'Slows down and bends away from normal', 'Travels in a straight line unaffected'], 1),
  mcq('The specific heat capacity of water is approximately:', 'Heat', ['4200 J/kg°C', '2100 J/kg°C', '1000 J/kg°C', '420 J/kg°C'], 0),
  mcq('A generator converts:', 'Electromagnetism', ['Electrical energy to mechanical energy', 'Mechanical energy to electrical energy', 'Chemical energy to electrical energy', 'Heat energy to electrical energy'], 1),
  { type: 'true_false', text: 'The acceleration due to gravity on Earth is approximately 9.8 m/s².', topic: 'Mechanics (motion)', answer: 'True' },
  { type: 'true_false', text: 'Sound waves can travel through a vacuum.', topic: 'Waves and optics', answer: 'False' },
  { type: 'true_false', text: 'Resistors in series have the same current flowing through each of them.', topic: 'Electricity', answer: 'True' },
  { type: 'true_false', text: 'Momentum is a scalar quantity.', topic: 'Momentum', answer: 'False' },
  { type: 'true_false', text: 'Alpha particles are more penetrating than gamma rays.', topic: 'Radioactivity', answer: 'False' },
  { type: 'true_false', text: 'Pressure in a fluid increases with depth.', topic: 'Pressure', answer: 'True' },
  {
    type: 'matching',
    text: 'Match each physical quantity with its correct SI unit.',
    topic: 'Units and measurements',
    pairs: [
      { left: 'Force', right: 'Newton (N)' },
      { left: 'Energy', right: 'Joule (J)' },
      { left: 'Power', right: 'Watt (W)' },
      { left: 'Electric current', right: 'Ampere (A)' },
      { left: 'Frequency', right: 'Hertz (Hz)' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each law of physics with its correct statement.',
    topic: 'Laws of physics',
    pairs: [
      { left: 'Newton\'s first law', right: 'An object remains at rest or in uniform motion unless acted on by a net force' },
      { left: 'Newton\'s third law', right: 'For every action there is an equal and opposite reaction' },
      { left: 'Ohm\'s law', right: 'Current is directly proportional to voltage at constant temperature' },
      { left: 'Law of conservation of energy', right: 'Energy cannot be created or destroyed, only transformed' },
      { left: 'Boyle\'s law', right: 'Pressure is inversely proportional to volume at constant temperature' },
    ],
  },
  {
    type: 'matching',
    text: 'Match each term related to waves with its correct definition.',
    topic: 'Waves and optics',
    pairs: [
      { left: 'Wavelength', right: 'The distance between two successive crests of a wave' },
      { left: 'Frequency', right: 'The number of waves passing a point per second' },
      { left: 'Amplitude', right: 'The maximum displacement of a wave from equilibrium' },
      { left: 'Reflection', right: 'The bouncing back of a wave from a surface' },
      { left: 'Refraction', right: 'The bending of a wave as it passes from one medium to another' },
    ],
  },
  { type: 'fill_blank', text: 'The formula for kinetic energy is KE = ______.', topic: 'Energy', answer: '½mv²' },
  { type: 'fill_blank', text: 'According to the principle of conservation of momentum, the total momentum before a collision equals the total momentum ______ the collision, provided no external force acts.', topic: 'Momentum', answer: 'after' },
  { type: 'fill_blank', text: 'The unit for electrical power is the ______.', topic: 'Electricity', answer: 'Watt' },
  { type: 'fill_blank', text: 'Pressure is defined as force per unit ______.', topic: 'Pressure', answer: 'area' },
  {
    type: 'short_answer',
    text: 'A car of mass 1000 kg accelerates from rest to 15 m/s in 5 seconds. Calculate the force required, assuming uniform acceleration.',
    topic: 'Mechanics (forces)',
    answer: 'a = (v - u)/t = (15 - 0)/5 = 3 m/s². F = ma = 1000 × 3 = 3000 N.',
    rubric: ['Correct acceleration formula and value = 3 m/s² (2 marks)', 'Correct application of F = ma (1 mark)', 'Correct final answer = 3000 N (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'A circuit has a 12 V battery connected to a resistor. If the current flowing is 3 A, calculate the resistance and the power dissipated.',
    topic: 'Electricity',
    answer: 'R = V/I = 12/3 = 4 Ω. P = VI = 12 × 3 = 36 W.',
    rubric: ['Correct resistance formula and value = 4 Ω (2 marks)', 'Correct power formula (1 mark)', 'Correct power value = 36 W (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'Calculate the kinetic energy of a bicycle and rider of total mass 60 kg moving at 4 m/s.',
    topic: 'Energy',
    answer: 'KE = ½mv² = 0.5 × 60 × 4² = 0.5 × 60 × 16 = 480 J.',
    rubric: ['Correct formula stated (1 mark)', 'Correct substitution (2 marks)', 'Correct final answer = 480 J (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'Two balls of mass 2 kg and 3 kg move towards each other at 4 m/s and 2 m/s respectively and collide, sticking together. Find their common velocity after collision.',
    topic: 'Momentum',
    answer: 'Taking the 2 kg ball direction as positive: momentum = (2×4) + (3×-2) = 8 - 6 = 2 kg·m/s. Combined mass = 5 kg. v = 2/5 = 0.4 m/s in the direction of the 2 kg ball.',
    rubric: ['Correct momentum before collision (2 marks)', 'Correct combined mass (1 mark)', 'Correct final velocity = 0.4 m/s (2 marks)'],
  },
  {
    type: 'short_answer',
    text: 'Explain, using three key points, why a manometer can be used to measure the pressure of a gas.',
    topic: 'Pressure',
    answer: 'A manometer contains a liquid whose height difference is directly related to pressure difference. The formula P = hρg relates height (h), density (ρ) of the liquid, and gravitational field strength (g) to pressure. By measuring the height difference of the liquid columns, the gas pressure can be calculated relative to atmospheric pressure.',
    rubric: ['States that height difference relates to pressure (2 marks)', 'States/uses the formula P = hρg (2 marks)', 'Explains comparison to atmospheric pressure (1 mark)'],
  },
  {
    type: 'short_answer',
    text: 'A radioactive isotope has a half-life of 8 days. If the initial mass is 40 g, calculate the mass remaining after 24 days.',
    topic: 'Radioactivity',
    answer: 'Number of half-lives = 24/8 = 3. Remaining mass = 40 × (1/2)³ = 40 × 1/8 = 5 g.',
    rubric: ['Correct number of half-lives = 3 (2 marks)', 'Correct application of decay formula (1 mark)', 'Correct final answer = 5 g (2 marks)'],
  },
  {
    type: 'structured',
    text: 'A stone is dropped from a bridge over the Akagera River from a height of 45 m above the water surface, with negligible air resistance (g = 10 m/s²).',
    topic: 'Mechanics (motion)',
    parts: [
      { text: 'Calculate the time taken for the stone to reach the water.', answer: 'h = ½gt² → 45 = ½ × 10 × t² → t² = 9 → t = 3 s.' },
      { text: 'Calculate the velocity of the stone just before it hits the water.', answer: 'v = gt = 10 × 3 = 30 m/s.' },
      {
        text: 'Consider the energy of the stone, given its mass is 0.5 kg.',
        parts: [
          { text: 'Calculate the kinetic energy of the stone just before impact.', answer: 'KE = ½mv² = 0.5 × 0.5 × 30² = 0.5 × 0.5 × 900 = 225 J.' },
          { text: 'Calculate the initial potential energy of the stone at the top of the bridge and comment on the result.', answer: 'PE = mgh = 0.5 × 10 × 45 = 225 J. This equals the kinetic energy calculated, confirming conservation of mechanical energy.' },
        ],
      },
    ],
  },
  {
    type: 'structured',
    text: 'A water tank in Nyagatare is being filled by a pump. The volume of water V (in litres) increases with time according to V(t) = 15t, where t is in minutes, and the tank has a cross-sectional area of 2 m².',
    topic: 'Pressure and fluids',
    parts: [
      { text: 'Calculate the volume of water after 10 minutes.', answer: 'V(10) = 15 × 10 = 150 litres.' },
      { text: 'Given 1000 litres = 1 m³, find the height of water in the tank after 10 minutes.', answer: '150 litres = 0.15 m³. Height = Volume/Area = 0.15/2 = 0.075 m.' },
      {
        text: 'Consider the pressure exerted by the water at the base of the tank (density of water = 1000 kg/m³, g = 10 m/s²).',
        parts: [
          { text: 'Calculate the pressure at the base of the tank after 10 minutes.', answer: 'P = hρg = 0.075 × 1000 × 10 = 750 Pa.' },
          { text: 'State how the pressure at the base would change if the tank were twice as wide (cross-sectional area doubled), for the same volume of water.', answer: 'A wider tank means the same volume gives a smaller height of water, so the pressure at the base would decrease (since P depends on height, not volume).' },
        ],
      },
    ],
  },
  {
    type: 'structured',
    text: 'A cooperative workshop in Huye uses an electric heater connected to a 220 V supply with a current of 5 A flowing through it for 2 hours daily.',
    topic: 'Electricity',
    parts: [
      { text: 'Calculate the power rating of the heater.', answer: 'P = VI = 220 × 5 = 1100 W = 1.1 kW.' },
      { text: 'Calculate the energy consumed by the heater in one day, in kilowatt-hours.', answer: 'Energy = Power × time = 1.1 kW × 2 h = 2.2 kWh.' },
      {
        text: 'The cooperative is billed at FRW 200 per kWh.',
        parts: [
          { text: 'Calculate the cost of running the heater for one day.', answer: 'Cost = 2.2 × 200 = FRW 440.' },
          { text: 'Calculate the cost of running the heater for 30 days.', answer: 'Cost = 440 × 30 = FRW 13,200.' },
        ],
      },
    ],
  },
  {
    type: 'structured',
    text: 'A sample of a radioactive isotope used in a hospital in Kigali has an initial activity of 800 counts per second and a half-life of 6 hours.',
    topic: 'Radioactivity',
    parts: [
      { text: 'Calculate the activity of the sample after 12 hours.', answer: 'Number of half-lives = 12/6 = 2. Activity = 800 × (1/2)² = 800 × 1/4 = 200 counts/s.' },
      { text: 'Calculate the activity of the sample after 18 hours.', answer: 'Number of half-lives = 18/6 = 3. Activity = 800 × (1/2)³ = 800 × 1/8 = 100 counts/s.' },
      {
        text: 'A technician needs to know when the sample becomes safe, defined as activity below 50 counts/s.',
        parts: [
          { text: 'Determine the number of half-lives needed for activity to fall below 50 counts/s.', answer: '800 × (1/2)ⁿ < 50 → (1/2)ⁿ < 1/16 → n > 4, so 4 half-lives are needed (n = 4 gives 50 exactly, so more than 4 half-lives, i.e. n = 5).' },
          { text: 'Calculate the corresponding time in hours.', answer: 'Time = 5 × 6 = 30 hours (using n = 5 half-lives to ensure activity is safely below 50 counts/s).' },
        ],
      },
    ],
  },
  {
    type: 'essay',
    text: 'Discuss the applications of electromagnetic induction in modern technology, with reference to at least two devices used in Rwanda, such as generators or transformers.',
    topic: 'Electromagnetism (application)',
    rubric: [
      'Correctly explains the principle of electromagnetic induction',
      'Describes the working of a generator or transformer',
      'Gives at least two real-life applications relevant to Rwanda (e.g. hydropower stations, transformers on the grid)',
      'Draws a clear, well-organised conclusion',
    ],
  },
  {
    type: 'essay',
    text: 'Investigate the factors affecting the resistance of a wire and discuss their practical significance in designing electrical circuits.',
    topic: 'Electricity (application)',
    rubric: [
      'Identifies factors: length, cross-sectional area, resistivity, and temperature',
      'Explains the relationship between resistance and each factor using R = ρL/A',
      'Gives a practical example of how this is applied (e.g. choice of cable thickness)',
      'Provides a logical conclusion linking theory to circuit design',
    ],
  },
  {
    type: 'essay',
    text: 'Discuss the uses and dangers of radioactivity, and explain the safety precautions that should be taken when handling radioactive materials in a hospital or research setting in Rwanda.',
    topic: 'Radioactivity (application)',
    rubric: [
      'States at least two beneficial uses of radioactivity (e.g. medical diagnosis/treatment, sterilisation)',
      'Explains at least two dangers of exposure to radioactivity',
      'Describes appropriate safety precautions (e.g. shielding, limited exposure time, distance)',
      'Concludes with a balanced assessment of benefits versus risks',
    ],
  },
];
