/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormatCheckRouteImport } from './routes/format-check'
import { Route as ExamIdRouteImport } from './routes/exam.$id'
import { Route as ExamIdIndexRouteImport } from './routes/exam.$id.index'
import { Route as ExamIdEditRouteImport } from './routes/exam.$id.edit'
import { Route as ExamIdGuideRouteImport } from './routes/exam.$id.guide'
import { Route as ExamIdPrintRouteImport } from './routes/exam.$id.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatCheckRoute = FormatCheckRouteImport.update({
  id: '/format-check',
  path: '/format-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIdRoute = ExamIdRouteImport.update({
  id: '/exam/$id',
  path: '/exam/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIdIndexRoute = ExamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamIdRoute,
} as any)
const ExamIdEditRoute = ExamIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ExamIdRoute,
} as any)
const ExamIdGuideRoute = ExamIdGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => ExamIdRoute,
} as any)
const ExamIdPrintRoute = ExamIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => ExamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/format-check': typeof FormatCheckRoute
  '/exam/$id': typeof ExamIdRouteWithChildren
  '/exam/$id/edit': typeof ExamIdEditRoute
  '/exam/$id/guide': typeof ExamIdGuideRoute
  '/exam/$id/print': typeof ExamIdPrintRoute
  '/exam/$id/': typeof ExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/format-check': typeof FormatCheckRoute
  '/exam/$id/edit': typeof ExamIdEditRoute
  '/exam/$id/guide': typeof ExamIdGuideRoute
  '/exam/$id/print': typeof ExamIdPrintRoute
  '/exam/$id': typeof ExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/format-check': typeof FormatCheckRoute
  '/exam/$id': typeof ExamIdRouteWithChildren
  '/exam/$id/edit': typeof ExamIdEditRoute
  '/exam/$id/guide': typeof ExamIdGuideRoute
  '/exam/$id/print': typeof ExamIdPrintRoute
  '/exam/$id/': typeof ExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/format-check'
    | '/exam/$id'
    | '/exam/$id/edit'
    | '/exam/$id/guide'
    | '/exam/$id/print'
    | '/exam/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/format-check'
    | '/exam/$id/edit'
    | '/exam/$id/guide'
    | '/exam/$id/print'
    | '/exam/$id'
  id:
    | '__root__'
    | '/'
    | '/format-check'
    | '/exam/$id'
    | '/exam/$id/edit'
    | '/exam/$id/guide'
    | '/exam/$id/print'
    | '/exam/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormatCheckRoute: typeof FormatCheckRoute
  ExamIdRoute: typeof ExamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/format-check': {
      id: '/format-check'
      path: '/format-check'
      fullPath: '/format-check'
      preLoaderRoute: typeof FormatCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$id': {
      id: '/exam/$id'
      path: '/exam/$id'
      fullPath: '/exam/$id'
      preLoaderRoute: typeof ExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$id/': {
      id: '/exam/$id/'
      path: '/'
      fullPath: '/exam/$id/'
      preLoaderRoute: typeof ExamIdIndexRouteImport
      parentRoute: typeof ExamIdRoute
    }
    '/exam/$id/edit': {
      id: '/exam/$id/edit'
      path: '/edit'
      fullPath: '/exam/$id/edit'
      preLoaderRoute: typeof ExamIdEditRouteImport
      parentRoute: typeof ExamIdRoute
    }
    '/exam/$id/guide': {
      id: '/exam/$id/guide'
      path: '/guide'
      fullPath: '/exam/$id/guide'
      preLoaderRoute: typeof ExamIdGuideRouteImport
      parentRoute: typeof ExamIdRoute
    }
    '/exam/$id/print': {
      id: '/exam/$id/print'
      path: '/print'
      fullPath: '/exam/$id/print'
      preLoaderRoute: typeof ExamIdPrintRouteImport
      parentRoute: typeof ExamIdRoute
    }
  }
}

interface ExamIdRouteChildren {
  ExamIdEditRoute: typeof ExamIdEditRoute
  ExamIdGuideRoute: typeof ExamIdGuideRoute
  ExamIdPrintRoute: typeof ExamIdPrintRoute
  ExamIdIndexRoute: typeof ExamIdIndexRoute
}

const ExamIdRouteChildren: ExamIdRouteChildren = {
  ExamIdEditRoute: ExamIdEditRoute,
  ExamIdGuideRoute: ExamIdGuideRoute,
  ExamIdPrintRoute: ExamIdPrintRoute,
  ExamIdIndexRoute: ExamIdIndexRoute,
}

const ExamIdRouteWithChildren =
  ExamIdRoute._addFileChildren(ExamIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormatCheckRoute: FormatCheckRoute,
  ExamIdRoute: ExamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
